/*
 * CMake autogenerated build_config.h file.
 * Make changes to build_config.h.cmake instead of this file.
 */

/*
  Copyright (c) 2010 Robert G. Jakabosky
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.

  MIT License: http://www.opensource.org/licenses/mit-license.php
*/

#ifndef __SLUA_BUILD_CONFIG_H__
#define __SLUA_BUILD_CONFIG_H__

/* lua config */
#cmakedefine LUA_BUILD_AS_DLL
#cmakedefine LUA_USE_MACOSX
#cmakedefine LUA_USE_DLOPEN
#cmakedefine LUA_USE_MKSTEMP
#cmakedefine LUA_USE_ISATTY
#cmakedefine LUA_USE_POPEN
#cmakedefine LUA_USE_ULONGJMP
#cmakedefine LUA_USE_APICHECK
#cmakedefine LUA_ANSI
#cmakedefine LUA_USE_READLINE
#cmakedefine LUA_CPP_SUPPORT

/* Coco config. */
#cmakedefine COCO_DISABLE
#cmakedefine COCO_USE_SETJMP
#cmakedefine COCO_USE_UCONTEXT

#ifndef _WIN32
#cmakedefine COCO_DEFAULT_CSTACKSIZE
#ifdef COCO_DEFAULT_CSTACKSIZE
#undef COCO_DEFAULT_CSTACKSIZE
#define COCO_DEFAULT_CSTACKSIZE @COCO_DEFAULT_CSTACKSIZE@
#endif
#endif

#endif /* __SLUA_BUILD_CONFIG_H__ */
